### ISSUE TITLE
[Bug]: Shop crash in multiplayer

### ISSUE THREAD

**Issue by Stanek5** [dr3ams/Roguelike-Adventures-and-Dungeons-2#181]
### General Info

- [x] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

TLauncher

### Modpack version

RAD2 - 0.96a [MC1.16.5]

### Describe your issue

When I try to open shop, my game leaves the server and crash. It crashes only on multiplayer. I tried to open the shop on singleplayer and load into multiplayer afterwards, it still crashes when I try to open the shop. It happens to my friend too.

### Steps to reproduce the issue

1. Go to multiplayer
2. Load into server.
3. Open shop with keybind or through quest book.
4. Game leaves multiplayer server and crashes.

### Additional Information

[crash-2023-02-06_12.34.48-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10662548/crash-2023-02-06_12.34.48-client.txt)
[2023-02-06-2.log.gz](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10662556/2023-02-06-2.log.gz)

**Comment by DoctorMage** [comment]
tell the server owner to stop the server
go to server properties 
have online-mode=true not false
then start the server

the server having this option as false will end up causing crashes and other issues from pmmo data not saving correctly and shop causing a crash due to not being able to save information correctly
![image](https://user-images.githubusercontent.com/85318453/216972991-67d60994-6ad9-46b8-8e74-6324c37e90a8.png)
