### ISSUE TITLE
[Bug]: FTBshop balance

### ISSUE THREAD

**Issue by kub891** [dr3ams/Roguelike-Adventures-and-Dungeons-2#227]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

I can't use my coins in ftbshop, but if i do /ftbbalance i see i have 1k coins. Can't buy anything in shop

### Additional Information

bug

**Comment by VanyaBaou** [comment]
Might be a bug from older versions (1.12.2 had this)
Pay yourself using commands and it should update your coins properly (this shouldn't require cheats, its paying yourself your own money)

**Comment by kub891** [comment]
I can't i got chat message WIP!

**Comment by DoctorMage** [comment]
Are you the server owner does shop work for other players?

**Comment by kub891** [comment]
i am the server owner, when other players try to open the shop their game crashes

**Comment by DoctorMage** [comment]
tell the server owner to stop the server
go to server properties 
have online-mode=true not false
then start the server

the server having this option as false will end up causing crashes and other issues from pmmo data not saving correctly and shop causing a crash due to not being able to save information correctly
![image](https://user-images.githubusercontent.com/85318453/225945053-db722d98-9223-479b-959b-ffdcf1554dce.png)

**Comment by thecortezz** [comment]
i'm having the same problem with the server crashing when opening the shop menu, is there any way to resolve this without taking the server to online-mode=true?

**Comment by DoctorMage** [comment]
no @thecortezz
