### ISSUE TITLE
[Bug]: No drops from Corail Tombstone with RAD2 1.6

### ISSUE THREAD

**Issue by trizmark** [dr3ams/Roguelike-Adventures-and-Dungeons-2#343]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism Launcher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

With the latest version (1.6) of the modpack I am getting no grave dust or essence of undeath drops from undead mobs. These drops are from Corail Tombstone, which has been updated between 1.5 and 1.6.
RAD2 1.5 had v8.6.12, while 1.6 has v8.6.13. I tried updating Corail Tombstone to v8.6.14, but no luck. I rolled back to v8.6.12 (all other mods are at RAD2 1.6 level) and the first zombie dropped grave dust!

I tried Corail Tombstone on its own in a 1.16.5 world and all aforementioned version provide a drop, which suggests that another mod is interfering with the drops.

### Additional Information

n/a

**Comment by epicTABmaster** [comment]
I have the exact same issue. I have only gotten one grave dust and I believe it was found in a chest. I didn't know if I was just unlucky but it would make more sense if it was a bug.

**Comment by DoctorMage** [comment]
Apologies for no response

the cause is something caused corail config to wipe the loot section

https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/53fd6f2860cd4e8f80f16b49b86d366906b5d53c

for now easiest option is to download 1.5 and import its config to 1.6

reset the config by deleting it tombstone-common.toml (this might mess with intended modpack changes)

the discord also cotains the correct config (https://discord.com/channels/512339624627011586/987711713572974612/1151936505418362971)

**Comment by trizmark** [comment]
No worries - glad the issue was found!
