### ISSUE TITLE
[Bug]: Project MMO has failed to load correctly (Server startup)

### ISSUE THREAD

**Issue by UnknownBlader** [dr3ams/Roguelike-Adventures-and-Dungeons-2#58]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.8

### Describe your issue

Project MMO has failed to load correctly

### Steps to reproduce the issue

Run LaunchServer.bat and in cmd it shows  Project MMO (pmmo) has failed to load correctly

### Additional Information

[crash-2022-11-20_19.17.39-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10049484/crash-2022-11-20_19.17.39-fml.txt)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10049485/latest.log)

**Comment by DoctorMage** [comment]
Java Version: 11.0.12, Oracle Corporation

You need to be using java 8

**Comment by DoctorMage** [comment]
Looks like you have Java 9 - 18 installed.
You need to specify Java 8 path in .bat file.

1. Download Java 8 here https://www.java.com/en/download/manual.jsp (Offline or Online instal)
2. Go to C:\Program Files\Java and see what Java version you have. You need the one starting with 1.8.0...

![image](https://user-images.githubusercontent.com/85318453/204135184-b221dadc-57f4-4f2e-b9e5-3755cf4ad925.png)

3. Right here I have jre1.8.0_291 That's the one we need! Probably for you it will be different.
4. Now you need to specify the exact path in .bat:
5. Open LaunchServer.bat with notepad
6. Instead of Java specify your full path to Java
7. For me the whole file would look like this:
 "C:\Program Files\Java\jre1.8.0_291\bin\java.exe" -Xmx4G -jar forge-1.16.5-36.2.33.jar nogui pause
 
![image](https://user-images.githubusercontent.com/85318453/204135263-351165d4-1ffb-4f23-a3f7-1987f271484a.png)

**Comment by UnknownBlader** [comment]
thanks tested and working :>

**Comment by Milmar06** [comment]
hey. for me there's no "jre1.8.0....." file, only "jre-1.8" and the server doesnt even want to start. what am i doing wrong? i tried to specify it to ("C:\Program Files\Java\jre-1.8\bin\java.exe" -Xmx4G -jar forge-1.16.5-36.2.33.jar nogui pause) but then it doesnt even want to open the batch file.

**Comment by UnknownBlader** [comment]
you need to install java 8 https://www.java.com/en/download/manual.jsp
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58#issuecomment-1752050091
